### ISSUE TITLE
success is not a function

### ISSUE THREAD

**Issue by kostia-lev** [eddiemoore/angular-spotify#51]
TypeError: $http(...).success is not a function
    at NgSpotify.api (vendor.js:41735)
    at NgSpotify.getAlbum (vendor.js:41765)
    at root.controller.js:19
    at Scope.$emit (vendor.js:18425)
    at SearchInputController.ctrl.onclick (searchinput.controller.js:8)
    at fn (eval at compile (vendor.js:15351), <anonymous>:4:177)
    at callback (vendor.js:26969)
    at Scope.$eval (vendor.js:18172)
    at Scope.$apply (vendor.js:18272)
    at HTMLDivElement.<anonymous> (vendor.js:26974)

**Comment by eddiemoore** [comment]
Just published an updated version (1.4.3) which is updated to work with angular 1.6
